name: Nightly Sync

on:
  schedule:
    - cron: "0 5 * * *"

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Lokalise v2 CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh

      - name: Run a multi-line script
        env:
          LOKALISE_PROJECT: ${{ secrets.GITHUB_TOKEN }}
          LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}
        run: |
          lokalise2 \
            --token $LOKALISE_TOKEN \
            --project-id $LOKALISE_PROJECT \
            file download \
            --format json \
            --export-sort a_z \
            --unzip-to ./
